# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  versioning: true
  param_fetcher_listener:  true
  allowed_methods_listener:  true
  routing_loader: true
  view:
    formats:  #uses de JMSserializer
      json: true
      html: false
    templating_formats:     #uses templating
      html: true
      json: false
    view_response_listener:  'force'
  #      exception:
  #          codes:
  #              App\Exception\MyException: 403
  #          messages:
  #              App\Exception\MyException: Forbidden area.
  format_listener:
    enabled: true
    rules:
      - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
      - { path: ^/, prefer_extension: true, priorities: [ 'html' ] }